//This file was generated by "gen_type_list.py".
#include "def/rcp_type.h"
#include "def/rcp_data.h"

rcp_extern void rcp_pointer_copy(
		rcp_type_ref type, rcp_data_ref src, rcp_data_ref dst);
rcp_extern int rcp_pointer_compare(
		rcp_type_ref ex, rcp_data_ref l, rcp_data_ref r);

rcp_extern void rcp_uint8_copy(
		rcp_type_ref type, rcp_data_ref src, rcp_data_ref dst);
rcp_extern int rcp_uint8_compare(
		rcp_type_ref ex, rcp_data_ref l, rcp_data_ref r);

rcp_extern void rcp_uint16_copy(
		rcp_type_ref type, rcp_data_ref src, rcp_data_ref dst);
rcp_extern int rcp_uint16_compare(
		rcp_type_ref ex, rcp_data_ref l, rcp_data_ref r);

rcp_extern void rcp_uint32_copy(
		rcp_type_ref type, rcp_data_ref src, rcp_data_ref dst);
rcp_extern int rcp_uint32_compare(
		rcp_type_ref ex, rcp_data_ref l, rcp_data_ref r);

rcp_extern void rcp_uint64_copy(
		rcp_type_ref type, rcp_data_ref src, rcp_data_ref dst);
rcp_extern int rcp_uint64_compare(
		rcp_type_ref ex, rcp_data_ref l, rcp_data_ref r);

rcp_extern void rcp_int8_copy(
		rcp_type_ref type, rcp_data_ref src, rcp_data_ref dst);
rcp_extern int rcp_int8_compare(
		rcp_type_ref ex, rcp_data_ref l, rcp_data_ref r);

rcp_extern void rcp_int16_copy(
		rcp_type_ref type, rcp_data_ref src, rcp_data_ref dst);
rcp_extern int rcp_int16_compare(
		rcp_type_ref ex, rcp_data_ref l, rcp_data_ref r);

rcp_extern void rcp_int32_copy(
		rcp_type_ref type, rcp_data_ref src, rcp_data_ref dst);
rcp_extern int rcp_int32_compare(
		rcp_type_ref ex, rcp_data_ref l, rcp_data_ref r);

rcp_extern void rcp_int64_copy(
		rcp_type_ref type, rcp_data_ref src, rcp_data_ref dst);
rcp_extern int rcp_int64_compare(
		rcp_type_ref ex, rcp_data_ref l, rcp_data_ref r);

rcp_extern void rcp_float_copy(
		rcp_type_ref type, rcp_data_ref src, rcp_data_ref dst);
rcp_extern int rcp_float_compare(
		rcp_type_ref ex, rcp_data_ref l, rcp_data_ref r);

rcp_extern void rcp_double_copy(
		rcp_type_ref type, rcp_data_ref src, rcp_data_ref dst);
rcp_extern int rcp_double_compare(
		rcp_type_ref ex, rcp_data_ref l, rcp_data_ref r);
