//This file was generated by "gen_type_list.py".
#include "def/rcp_type.h"

#define RCP_TYPE_NULL ((rcp_type_id_t)0)
extern const rcp_type_ref rcp_null_type;

#define RCP_TYPE_REF ((rcp_type_id_t)1)
extern const rcp_type_ref rcp_ref_type;

#define RCP_TYPE_POINTER ((rcp_type_id_t)2)
extern const rcp_type_ref rcp_pointer_type;

#define RCP_TYPE_STRING ((rcp_type_id_t)20)
extern const rcp_type_ref rcp_string_type;

#define RCP_TYPE_BOOL8 ((rcp_type_id_t)25)
extern const rcp_type_ref rcp_bool8_type;

#define RCP_TYPE_BOOL32 ((rcp_type_id_t)26)
extern const rcp_type_ref rcp_bool32_type;

#define RCP_TYPE_UINT8 ((rcp_type_id_t)32)
extern const rcp_type_ref rcp_uint8_type;

#define RCP_TYPE_UINT16 ((rcp_type_id_t)33)
extern const rcp_type_ref rcp_uint16_type;

#define RCP_TYPE_UINT32 ((rcp_type_id_t)34)
extern const rcp_type_ref rcp_uint32_type;

#define RCP_TYPE_UINT64 ((rcp_type_id_t)35)
extern const rcp_type_ref rcp_uint64_type;

#define RCP_TYPE_INT8 ((rcp_type_id_t)40)
extern const rcp_type_ref rcp_int8_type;

#define RCP_TYPE_INT16 ((rcp_type_id_t)41)
extern const rcp_type_ref rcp_int16_type;

#define RCP_TYPE_INT32 ((rcp_type_id_t)42)
extern const rcp_type_ref rcp_int32_type;

#define RCP_TYPE_INT64 ((rcp_type_id_t)43)
extern const rcp_type_ref rcp_int64_type;

#define RCP_TYPE_FLOAT ((rcp_type_id_t)49)
extern const rcp_type_ref rcp_float_type;

#define RCP_TYPE_DOUBLE ((rcp_type_id_t)50)
extern const rcp_type_ref rcp_double_type;
#ifdef RCP_INTERNAL_STRUCTURE

extern struct rcp_type_core rcp_null_type_def;

extern struct rcp_type_core rcp_ref_type_def;

extern struct rcp_type_core rcp_pointer_type_def;

extern struct rcp_type_core rcp_string_type_def;

extern struct rcp_type_core rcp_bool8_type_def;

extern struct rcp_type_core rcp_bool32_type_def;

extern struct rcp_type_core rcp_uint8_type_def;

extern struct rcp_type_core rcp_uint16_type_def;

extern struct rcp_type_core rcp_uint32_type_def;

extern struct rcp_type_core rcp_uint64_type_def;

extern struct rcp_type_core rcp_int8_type_def;

extern struct rcp_type_core rcp_int16_type_def;

extern struct rcp_type_core rcp_int32_type_def;

extern struct rcp_type_core rcp_int64_type_def;

extern struct rcp_type_core rcp_float_type_def;

extern struct rcp_type_core rcp_double_type_def;
#endif
